name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - website  # Adjust this to your development branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          # pip install -r requirements.txt  # If you have other dependencies

      - name: Build Sphinx documentation
        run: |
          cd _website
          make html  # This will build the docs into _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_website/_build/html
          publish_branch: gh-pages  # This will deploy to the gh-pages branch
