name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust based on your Jekyll version
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: |
          cd _website
          bundle install

      - name: Build Jekyll site
        run: |
          cd _website
          bundle exec jekyll build --destination ../_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: _site
          publish_branch: gh-pages

